sudo: required
services:
  - docker
before_install:
  - docker build -t jeremymiller/weather .
  - docker run -it --rm jeremymiller/weather go get github.com/mattn/goveralls
script:
  - docker run -it --rm jeremymiller/weather go test
after_success:
  - docker run -it --rm jeremymiller/weather goveralls -repotoken $COVERALLS_REPO_TOKEN
